### ISSUE TITLE
Enforce prettier rules

### ISSUE THREAD

**Issue by henryruhs** [AlexMelov/FullStackApp#55]
There should be a prettier check inside husky and inside the CI pipeline.

**Comment by AlexMelov** [comment]
- [x] Prettier is set but when I reformat code he remove empty spaces and return the bracket on the start line. I was searching for rule for that but from this point I don't know what to do with Prettier since he can't be used strictly for one rule as example to set only singleQuote but not removing the empty spaces and set bracket in start line.

**Comment by AlexMelov** [comment]
Removed

**Comment by henryruhs** [comment]
I seached for it and it turns out that the prettier does not support the Allman indent style. Therefore I close that issue, sorry for wasting time.
